package de.hochschuletrier.gdw.ws1314.entity;

/**
 * Created by Jerry on 20.03.14.
 */
public enum EventType {
	IDLE,
    WALK_GRASS,
	WALK_BRIDGE,
	WALK_WAY,
    KNOCKBACK,
    PUSH_BLOCK,
    ATTACK_1,
    ATTACK_2,
    HIT_BY_ATTACK_1,
    HIT_BY_ATTACK_2,
	KO,
	SCORED,
	FALLEN,
	DRWONING,
    DESTROY,
	BRIDGE_OUT,
	BRIDGE_IN,
	SWITCH,
    DIE_WATER,
    DIE_ABYSS,
    DIE_PLAYER,
	EAT_PICKUP,
	BUFF_ACTIVATE_CARROT,
	BUFF_ACTIVATE_SPINACH,
	BUFF_DEACTIVATE_CARROT,
	BUFF_DEACTIVATE_SPINACH,
	BUFF_EAT_CLOVER,
    EGG_PICKUP,
    EGG_DROP,
    
    
    ANY
}
